# Generated by Django 5.1.5 on 2025-02-15 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0002_delete_featuredproduct_delete_homepage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Catégories', 'verbose_name_plural': 'Catégories'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Commandes', 'verbose_name_plural': 'Commandes'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Produits', 'verbose_name_plural': 'Produits'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Profils des utilisateurs', 'verbose_name_plural': 'Profils des utilisateurs'},
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('shipped', 'Expédié'), ('delivered', 'Livré'), ('cancelled', 'Annulé')], max_length=50),
        ),
    ]
