# Generated by Django 5.1.5 on 2025-01-20 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_product_category_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutUs',
        ),
        migrations.DeleteModel(
            name='ContactInfo',
        ),
        migrations.DeleteModel(
            name='FAQ',
        ),
        migrations.DeleteModel(
            name='GeneralContent',
        ),
        migrations.DeleteModel(
            name='ReturnPolicy',
        ),
        migrations.DeleteModel(
            name='TermsAndConditions',
        ),
    ]
