# Generated by Django 5.1.5 on 2025-02-15 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_delete_aboutus_delete_contactinfo_delete_faq_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'verbose_name': 'Article de blog', 'verbose_name_plural': 'Articles de blog'},
        ),
    ]
