# Generated by Django 5.1.5 on 2025-03-15 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blogpost_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('skincare', 'Soins de la peau'), ('makeup', 'Maquillage'), ('fragrance', 'Parfums'), ('haircare', 'Soins capillaires'), ('natural', 'Produits naturels'), ('tips', 'Conseils beauté'), ('trends', 'Tendances cosmétiques'), ('reviews', 'Avis produits')], default='skincare', max_length=50),
        ),
    ]
