# Generated by Django 5.1.5 on 2025-01-20 11:15

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history', ckeditor.fields.RichTextField(help_text='Texte décrivant la création et les valeurs de Razana Healthy Cosmetics.')),
                ('mission', ckeditor.fields.RichTextField(help_text='Objectifs à long terme et engagement envers les clients.')),
                ('team_photo', models.ImageField(blank=True, null=True, upload_to='team_photos/')),
            ],
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('tiktok', models.URLField(blank=True, null=True)),
                ('google_maps_location', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GeneralContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(help_text='Logo de l’entreprise en haute résolution.', upload_to='logos/')),
                ('color_palette', ckeditor.fields.RichTextField(blank=True, help_text='Palette de couleurs et typographie.', null=True)),
                ('additional_media', models.FileField(blank=True, help_text='Médias supplémentaires comme icônes spécifiques, bannières publicitaires, etc.', null=True, upload_to='media/')),
            ],
            options={
                'verbose_name': 'Contenu général',
                'verbose_name_plural': 'Contenu général',
            },
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slogan', models.CharField(help_text='Court texte décrivant la mission ou les valeurs de l’entreprise.', max_length=255)),
                ('main_image', models.ImageField(help_text='Visuel de haute qualité représentant les produits.', upload_to='home_images/')),
                ('promo_video', models.FileField(blank=True, help_text='Vidéo promotionnelle (si disponible).', null=True, upload_to='home_videos/')),
            ],
        ),
        migrations.CreateModel(
            name='ReturnPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_text', ckeditor.fields.RichTextField(help_text='Politique de retour et d’échange.')),
            ],
        ),
        migrations.CreateModel(
            name='FeaturedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(upload_to='featured_products/')),
                ('home_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_products', to='rozana.homepage')),
            ],
        ),
    ]
