# Generated by Django 5.1.5 on 2025-04-28 20:57

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history', django_ckeditor_5.fields.CKEditor5Field(help_text='Texte décrivant la création et les valeurs de Razana Healthy Cosmetics.')),
                ('mission', django_ckeditor_5.fields.CKEditor5Field(help_text='Objectifs à long terme et engagement envers les clients.')),
                ('team_photo', models.ImageField(blank=True, null=True, upload_to='team_photos/')),
            ],
            options={
                'verbose_name': 'A propos de nous',
                'verbose_name_plural': 'A propos de nous',
            },
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('tiktok', models.URLField(blank=True, null=True)),
                ('google_maps_location', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Info contacts',
                'verbose_name_plural': 'Info contacts',
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('subject', models.CharField(max_length=255, verbose_name='Sujet')),
                ('message', models.TextField(verbose_name='Message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Message de contact',
                'verbose_name_plural': 'Messages de contact',
            },
        ),
        migrations.CreateModel(
            name='GeneralContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(help_text='Logo de l’entreprise en haute résolution.', upload_to='logos/')),
                ('color_palette', django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Palette de couleurs et typographie.', null=True)),
                ('additional_media', models.FileField(blank=True, help_text='Médias supplémentaires comme icônes spécifiques, bannières publicitaires, etc.', null=True, upload_to='media/')),
            ],
            options={
                'verbose_name': 'Contenu général',
                'verbose_name_plural': 'Contenu général',
            },
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slogan', models.CharField(help_text='Court texte décrivant la mission ou les valeurs de l’entreprise.', max_length=255)),
                ('promo_video', models.FileField(blank=True, help_text='Vidéo promotionnelle (si disponible).', null=True, upload_to='home_videos/')),
            ],
            options={
                'verbose_name': "Page d'accueil",
                'verbose_name_plural': "Pages d'accueil",
            },
        ),
        migrations.CreateModel(
            name='ReturnPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_text', django_ckeditor_5.fields.CKEditor5Field(help_text='Politique de retour et d’échange.')),
            ],
            options={
                'verbose_name': 'Politique de retour',
                'verbose_name_plural': 'Politique de retour',
            },
        ),
        migrations.CreateModel(
            name='FeaturedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', django_ckeditor_5.fields.CKEditor5Field()),
                ('image', models.ImageField(upload_to='featured_products/')),
                ('home_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_products', to='rozana.homepage')),
            ],
            options={
                'verbose_name': 'Produit phare',
                'verbose_name_plural': 'Produit phare',
            },
        ),
        migrations.CreateModel(
            name='HomePageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text="Images supplémentaires pour la page d'accueil.", upload_to='home_images/')),
                ('home_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='rozana.homepage')),
            ],
        ),
    ]
