# Generated by Django 5.1.5 on 2025-02-15 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rozana', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name': 'A propos de nous', 'verbose_name_plural': 'A propos de nous'},
        ),
        migrations.AlterModelOptions(
            name='contactinfo',
            options={'verbose_name': 'Info contacts', 'verbose_name_plural': 'Info contacts'},
        ),
        migrations.AlterModelOptions(
            name='featuredproduct',
            options={'verbose_name': 'Produit phare', 'verbose_name_plural': 'Produit phare'},
        ),
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': "Page d'accueil", 'verbose_name_plural': "Pages d'accueil"},
        ),
        migrations.AlterModelOptions(
            name='returnpolicy',
            options={'verbose_name': 'Politique de retour', 'verbose_name_plural': 'Politique de retour'},
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='main_image',
        ),
        migrations.CreateModel(
            name='HomePageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text="Images supplémentaires pour la page d'accueil.", upload_to='home_images/')),
                ('home_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='rozana.homepage')),
            ],
        ),
    ]
