# Generated by Django 5.1.5 on 2025-04-28 20:57

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', django_ckeditor_5.fields.CKEditor5Field()),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQ',
            },
        ),
        migrations.CreateModel(
            name='TermsAndConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(help_text='Texte légal détaillant les politiques de l’entreprise (paiement, livraison, retours, etc.).')),
            ],
            options={
                'verbose_name': 'Conditions générales',
                'verbose_name_plural': 'Conditions générales',
            },
        ),
    ]
