# Generated by Django 5.1.5 on 2025-02-15 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conditions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name': 'FAQ', 'verbose_name_plural': 'FAQ'},
        ),
        migrations.AlterModelOptions(
            name='termsandconditions',
            options={'verbose_name': 'Conditions générales', 'verbose_name_plural': 'Conditions générales'},
        ),
    ]
