"""
Django settings for rozana project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from django.utils.translation import gettext_lazy as _
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
#SECRET_KEY = config('SECRET_KEY')
SECRET_KEY = 'django-insecure-!omfusx(6!vqrxvg8s9+#r5obes2s(f6u1)(&q9409k@358&!g'


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['rozana-cosmetic.com','www.rozana-cosmetic.com','127.0.0.1']

CSRF_TRUSTED_ORIGINS = ['https://rozana-cosmetic.com','https://www.rozana-cosmetic.com']


# Application definition

INSTALLED_APPS = [
    'django_ckeditor_5',
    'grappelli',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'blog',
    'commerce',
    'conditions',
    'rozana'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', 


]

ROOT_URLCONF = 'rozana.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'rozana.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]
CKEDITOR_5_UPLOAD_PATH = "uploads/blog_images/"  
CKEDITOR_5_IMAGE_BACKEND = "pillow"  # Optionnel, mais recommandé
# Configurations de CKEditor 5
CKEDITOR_5_CONFIGS = {
    'default': {
        'toolbar': [
            'heading', '|',
            'bold', 'italic', 'underline', 'strikethrough', 'subscript', 'superscript', '|',
            'fontSize', 'fontFamily', 'fontColor', 'fontBackgroundColor', '|',
            'alignment', '|',
            'numberedList', 'bulletedList', '|',
            'outdent', 'indent', '|',
            'blockQuote', 'link', 'imageUpload', 'mediaEmbed', 'insertTable', '|',
            'code', 'codeBlock', '|',
            'horizontalLine', 'pageBreak', '|',
            'specialCharacters', 'smiley', '|',
            'findAndReplace', 'selectAll', '|',
            'sourceEditing', '|',
            'undo', 'redo', '|',
            'fullscreen'
        ],
        'height': '600px',
        'width': '100%',
        'language': 'fr',
        'image': {
            'toolbar': [
                'imageTextAlternative', '|',
                'imageStyle:inline', 'imageStyle:block', 'imageStyle:side', '|',
                'toggleImageCaption', '|',
                'imageResize:25', 'imageResize:50', 'imageResize:75', 'imageResize:original'
            ],
            'styles': [
                'full',
                'side',
                'alignLeft',
                'alignRight',
                'alignCenter'
            ]
        },
        'table': {
            'contentToolbar': [
                'tableColumn', 'tableRow', 'mergeTableCells', 
                'tableProperties', 'tableCellProperties'
            ],
            'tableProperties': {
                'borderColors': True,
                'backgroundColors': True
            }
        },
        'licenseKey': '',  # Laissez vide sauf si vous avez une clé pro
        'htmlSupport': {
            'allow': [
                {'name': 'div', 'classes': True},
                {'name': 'span', 'classes': True}
            ]
        },
        'link': {
            'decorators': {
                'openInNewTab': {
                    'mode': 'manual',
                    'label': 'Ouvrir dans un nouvel onglet',
                    'attributes': {
                        'target': '_blank',
                        'rel': 'noopener noreferrer'
                    }
                }
            }
        }
    }
}

GRAPPELLI_ADMIN_TITLE = "Rozana Admin"  # Custom title for the admin interface
GRAPPELLI_INDEX_DASHBOARD = 'rozana.dashboard.CustomIndexDashboard'

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

LOGIN_REDIRECT_URL = 'home'  # Redirige vers la page d'accueil après la connexion

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'fr'

TIME_ZONE = 'Etc/GMT-1'

USE_I18N = True

USE_TZ = True

LOGIN_URL = '/commerce/login/'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")  # Où les fichiers collectés seront stockés
STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]


MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

LANGUAGES = [
    ('en', _('English')),
    ('fr', _('Français')),
    ('ar', _('العربية')),
]

LOCALE_PATHS = [
    BASE_DIR / 'locale',
]


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

#Configuraton de mail settings
#(pour le développement uniquement)

#EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

#(pour la producton)

# EMAIL_BACKEND       = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST          = config('EMAIL_HOST')
# EMAIL_PORT          = config('EMAIL_PORT')
# EMAIL_HOST_USER     = config('EMAIL_HOST_USER')
# EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')
# EMAIL_USE_TLS       = True
# EMAIL_USE_SSL       = False
# DEFAULT_FROM_EMAIL  = config('DEFAULT_FROM_EMAIL')

# ADMIN_EMAIL         = config('ADMIN_EMAIL')

ADMIN_EMAIL = 'contact@rozana-cosmetic.com'

EMAIL_BACKEND       = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST          = 'smtp.gmail.com'
EMAIL_PORT          = 587
EMAIL_HOST_USER     = 'baytabourkouelie@gmail.com'
EMAIL_HOST_PASSWORD = "tzii ueig dted vejt"
DEFAULT_FROM_EMAIL  = 'Rozana Healthy cosmetics <baytabourkouelie@gmail.com>'
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False

#Twillo settings.py
# TWILIO_ACCOUNT_SID      = config('TWILIO_ACCOUNT_SID')
# TWILIO_AUTH_TOKEN       = config('TWILIO_AUTH_TOKEN')
# TWILIO_WHATSAPP_NUMBER  = config('TWILIO_WHATSAPP_NUMBER')
# ADMIN_WHATSAPP_NUMBER   = config('ADMIN_WHATSAPP_NUMBER')


ADMINS = [('Admin Rozana', 'baytabourkouelie@gmail.com'),]
